=== vitchurb/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType mixed="true">
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Project" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Group" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element name="GroupsForUser" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="GroupForUser"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="xs:string" name="email" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GroupForUser">
        <xs:complexType>
            <xs:attribute type="xs:IDREF" name="group" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="groupState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="Project" type="projectType"/>

    <xs:complexType name="projectType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="Group" type="groupType"/>

    <xs:complexType name="groupType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
                <xs:attribute type="groupState" name="state" use="required"/>
                <xs:attribute type="xs:IDREF" name="project" use="required"/>
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
</xs:schema>

=== vitchurb/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv" email="mail1@gmail.com">
            <fullName>Full Name</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava03"/>
                <GroupForUser group="masterjava03"/>
            </GroupsForUser>
        </User>
        <User flag="superuser" city="spb" email="pochta@mail.ru">
            <fullName>Admin</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava01"/>
                <GroupForUser group="topjava02"/>
                <GroupForUser group="topjava03"/>
                <GroupForUser group="topjava07"/>
                <GroupForUser group="topjava08"/>
                <GroupForUser group="masterjava01"/>
                <GroupForUser group="masterjava02"/>
                <GroupForUser group="masterjava03"/>
            </GroupsForUser>
        </User>
        <User flag="deleted" city="spb" email="nobody@gmail.com">
            <fullName>Deleted</fullName>
            <GroupsForUser>
            </GroupsForUser>
        </User>
        <User flag="active" city="spb" email="user5@gmail.com">
            <fullName>User5</fullName>
            <GroupsForUser>
                <GroupForUser group="masterjava03"/>
            </GroupsForUser>
        </User>
        <User flag="active" city="kiv" email="user6@gmail.com">
            <fullName>User6</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava01"/>
            </GroupsForUser>
        </User>
        <User flag="active" city="kiv" email="user7@gmail.com">
            <fullName>User7</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava01"/>
            </GroupsForUser>
        </User>
        <User flag="active" city="spb" email="user8@gmail.com">
            <fullName>User8</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava01"/>
            </GroupsForUser>
        </User>
        <User flag="active" city="spb" email="user9@gmail.com">
            <fullName>User9</fullName>
            <GroupsForUser>
                <GroupForUser group="topjava01"/>
            </GroupsForUser>
        </User>
    </Users>
    <Projects>
        <Project id="topjava">TopJava</Project>
        <Project id="masterjava">MasterJava</Project>
    </Projects>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Groups>
        <Group id="topjava01" project="topjava" state="FINISHED">TopJava 01</Group>
        <Group id="topjava02" project="topjava" state="FINISHED">TopJava 02</Group>
        <Group id="topjava03" project="topjava" state="FINISHED">TopJava 03</Group>
        <Group id="topjava07" project="topjava" state="FINISHED">TopJava 07</Group>
        <Group id="topjava08" project="topjava" state="REGISTERING">TopJava 08</Group>
        <Group id="masterjava01" project="masterjava" state="FINISHED">MasterJava 01</Group>
        <Group id="masterjava02" project="masterjava" state="CURRENT">MasterJava 02</Group>
        <Group id="masterjava03" project="masterjava" state="REGISTERING">MasterJava 03</Group>
    </Groups>
</Payload>
